version: '3.8'

services:
  backend:
    build: ./server
    ports:
      - "8000:8000"
    restart: always

  frontend:
    build: ./front2
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: always